#! /usr/bin/env lua
-- 1. open socket
-- 2. read socket for fullscreen
-- 3. send smth to waybar

local socket =  require("posix.sys.socket")
local unistd =  require("posix.unistd")
local fd =      assert(socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0))

XDRD =  os.getenv("XDG_RUNTIME_DIR")
HIS =   os.getenv("HYPRLAND_INSTANCE_SIGNATURE")

assert(socket.connect(fd, {family = socket.AF_UNIX, path = ""..XDRD.."/hypr/"..HIS.."/.socket2.sock"}))

local wsCache = {}

while true do
    bytes = assert(socket.recv(fd, 1337))
    --io.write(bytes)

    for i in string.gmatch(bytes, "%S+") do
        if string.find(i, "^workspace>>%d$") then -- find workspace that we are switching to
            ws,_ = (string.gsub(i,"workspace>>",""))
        end
        if string.find(i,"^fullscreen>>%d$") then
            fsState,_ = (string.gsub(i,"fullscreen>>",""))
            wsCache[ws] = fsstate
        end
    end
    print(wsCache)
    --if bytes == "fullscreen>>0\n" then
    --    print("not full")
    --elseif bytes == "fullscreen>>1\n" then
    --    print("full")
    --end

end
unistd.close(fd)

